spring:
  application:
    name: knowledge-mgmt-api
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/kmapi
    username: km
    password: km
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: INFO
